# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger: 
 - develop
 - feature/*

# pool:
#    vmImage: 'ubuntu-latest'

stages:
- stage: 'BuildTest'
  displayName: "Build and Test"
  variables:
    GOVERSION: "1.13.5"
    CGO_ENABLES: "0"
    GOOS: "linux"
    GOARCH: "amd64"
  jobs:
  - job: BuildTestBackend
    displayName: "Build and Test Go"
    pool:
      vmImage: 'Ubuntu 18.04'
      